# fly.toml app configuration file generated for digital-twin-zw-big on 2025-05-09T06:23:43Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'digital-twin-zw-big'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
